name: Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Determine next version
        id: get_version
        shell: pwsh
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag sorted by version (e.g. "1.3")
          $latestTag = git tag --sort=-version:refname | Select-Object -First 1
          if (-not $latestTag) {
            Write-Host "No tag found, defaulting to 0.1"
            $newTag = "0.1"
          }
          else {
            Write-Host "Latest tag: $latestTag"
            # Split into major and minor parts
            $parts = $latestTag -split '\.'
            $major = $parts[0]
            $minor = [int]$parts[1]
            $newTag = "$major.$($minor + 1)"
          }
          Write-Host "New tag: $newTag"
          # Export the new tag to the GitHub environment
          "NEW_TAG=$newTag" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create and push new tag
        shell: pwsh
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag $env:NEW_TAG
          git push origin $env:NEW_TAG

      - name: Create zip archive
        shell: pwsh
        run: |
          $zipName = "GoogleTranslateBFBB$env:NEW_TAG.zip"
          Compress-Archive -Path `
            "GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.dll", `
            "GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.dll.config", `
            "GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.exe", `
            "GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.runtimeconfig.json", `
            "HipHopTool/HipHopFile/bin/Release/HipHopFile.dll" `
            -DestinationPath $zipName
          Write-Host "Created zip archive: $zipName"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoogleTranslateBFBB
          path: GoogleTranslateBFBB${{ env.NEW_TAG }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: "Google Translate BFBB ${{ env.NEW_TAG }}"
          body: "Windows .NET 8.0 Build"
          draft: false
          prerelease: false
          files: GoogleTranslateBFBB${{ env.NEW_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
