name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Fetch all tags
        run: git fetch --tags --force

      - name: Get latest tag
        id: get_version
        run: |
          $TAG_VERSION = $(git describe --tags --abbrev=0 2>$null) 
          if (-not $TAG_VERSION) { $TAG_VERSION = "v0.0.1" } 
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Create zip archive
        run: |
          $zipName = "GoogleTranslateBFBBv${{ env.TAG_VERSION }}.zip"
          Compress-Archive -Path GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.dll, `
                           GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.dll.config, `
                           GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.exe, `
                           GoogleTranslateBFBBRewrite/bin/Release/net8.0-windows8.0/GoogleTranslateBFBBRewrite.runtimeconfig.json, `
                           HipHopTool/HipHopFile/bin/Release/HipHopFile.dll `
                           -DestinationPath $zipName

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoogleTranslateBFBB
          path: GoogleTranslateBFBBv${{ env.TAG_VERSION }}.zip

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_VERSION }}
          name: "Google Translate BFBB v${{ env.TAG_VERSION }}"
          body: "Windows .NET 8.0 Build"
          draft: false
          prerelease: false
          files: GoogleTranslateBFBBv${{ env.TAG_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
